const languages = [
  { label: "Afrikaans", value: "/auto/af" },
  { label: "Albanian", value: "/auto/sq" },
  { label: "Amharic", value: "/auto/am" },
  { label: "Arabic", value: "/auto/ar" },
  { label: "Azerbaijani", value: "/auto/az" },
  { label: "Basque", value: "/auto/eu" },
  { label: "Belarusian", value: "/auto/be" },
  { label: "Bulgarian", value: "/auto/bg" },
  { label: "Bengali", value: "/auto/bn" },
  { label: "Catalan", value: "/auto/ca" },
  { label: "Croatian", value: "/auto/hr" },
  { label: "Chinese (Simplified)", value: "/auto/zh-CN" },
  { label: "Chinese (Traditional)", value: "/auto/zh-TW" },
  { label: "Czech", value: "/auto/cs" },
  { label: "Danish", value: "/auto/da" },
  { label: "Dutch", value: "/auto/nl" },
  { label: "English", value: "/auto/en" },
  { label: "Estonian", value: "/auto/et" },
  { label: "Finnish", value: "/auto/fi" },
  { label: "Filipino", value: "/auto/tl" },
  { label: "French", value: "/auto/fr" },
  { label: "Georgian", value: "/auto/ka" },
  { label: "German", value: "/auto/de" },
  { label: "Greek", value: "/auto/el" },
  { label: "Hebrew", value: "/auto/he" },
  { label: "Hindi", value: "/auto/hi" },
  { label: "Hungarian", value: "/auto/hu" },
  { label: "Irish", value: "/auto/ga" },
  { label: "Indonesian", value: "/auto/id" },
  { label: "Italian", value: "/auto/it" },
  { label: "Japanese", value: "/auto/ja" },
  { label: "Kannada", value: "/auto/kn" },
  { label: "Kurdish", value: "/auto/ku" },
  { label: "Korean", value: "/auto/ko" },
  { label: "Latvian", value: "/auto/lv" },
  { label: "Lithuanian", value: "/auto/lt" },
  { label: "Luxembourgish", value: "/auto/lb" },
  { label: "Macedonian", value: "/auto/mk" },
  { label: "Malagasy", value: "/auto/mg" },
  { label: "Malay", value: "/auto/ms" },
  { label: "Malayalam", value: "/auto/ml" },
  { label: "Maltese", value: "/auto/mt" },
  { label: "Maori", value: "/auto/mi" },
  { label: "Marathi", value: "/auto/mr" },
  { label: "Myanmar (Burmese)", value: "/auto/my" },
  { label: "Mongolian", value: "/auto/mn" },
  { label: "Nepali", value: "/auto/ne" },
  { label: "Norwegian", value: "/auto/no" },
  { label: "Pashto", value: "/auto/ps" },
  { label: "Polish", value: "/auto/pl" },
  { label: "Portuguese", value: "/auto/pt" },
  { label: "Persian", value: "/auto/fa" },
  { label: "Punjabi", value: "/auto/pa" },
  { label: "Romanian", value: "/auto/ro" },
  { label: "Russian", value: "/auto/ru" },
  { label: "Somali", value: "/auto/so" },
  { label: "Serbian", value: "/auto/sr" },
  { label: "Slovak", value: "/auto/sk" },
  { label: "Slovenian", value: "/auto/sl" },
  { label: "Spanish", value: "/auto/es" },
  { label: "Swahili", value: "/auto/sw" },
  { label: "Swedish", value: "/auto/sv" },
  { label: "Tamil", value: "/auto/ta" },
  { label: "Telugu", value: "/auto/te" },
  { label: "Thai", value: "/auto/th" },
  { label: "Turkish", value: "/auto/tr" },
  { label: "Ukrainian", value: "/auto/uk" },
  { label: "Vietnamese", value: "/auto/vi" },
  { label: "Welsh", value: "/auto/cy" },
  { label: "Xhosa", value: "/auto/xh" },
  { label: "Yoruba", value: "/auto/yo" },
  { label: "Zulu", value: "/auto/zu" },
];

export default languages;
